"""create tanle

Revision ID: d23d5b02c4fb
Revises: 601b27fe7436
Create Date: 2024-04-29 23:59:22.210444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d23d5b02c4fb"
down_revision: Union[str, None] = "601b27fe7436"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Path_Table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column(
            "time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email"],
            ["User_Table.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Path_Table_email"), "Path_Table", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_Path_Table_path"), "Path_Table", ["path"], unique=True
    )
    op.create_table(
        "File_Table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email"],
            ["Path_Table.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_File_Table_name"), "File_Table", ["name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_File_Table_name"), table_name="File_Table")
    op.drop_table("File_Table")
    op.drop_index(op.f("ix_Path_Table_path"), table_name="Path_Table")
    op.drop_index(op.f("ix_Path_Table_email"), table_name="Path_Table")
    op.drop_table("Path_Table")
    # ### end Alembic commands ###
